# Generated by Django 5.2.15 on 2026-06-28 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[("lent", "Men berdim"), ("borrowed", "Men oldim")],
                        max_length=16,
                    ),
                ),
                ("counterparty", models.CharField(max_length=64)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "so'm"), ("RUB", "rubl"), ("USD", "dollar")],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                ("expected_return_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("partial", "Qisman qaytarilgan"),
                            ("closed", "Yopilgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "debts_debt",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DebtRepayment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("note", models.TextField(blank=True, default="")),
                ("repaid_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="debts.debt",
                    ),
                ),
            ],
            options={
                "db_table": "debts_debtrepayment",
                "ordering": ["repaid_at", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["user", "state", "direction"],
                name="debts_debt_user_id_12a492_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["user", "expected_return_date"],
                name="debts_debt_user_id_bfc30f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="debt",
            constraint=models.CheckConstraint(
                condition=models.Q(("original_amount__gt", 0)),
                name="debts_original_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="debt",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_amount__gte", 0)),
                name="debts_remaining_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="debt",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_amount__lte", models.F("original_amount"))),
                name="debts_remaining_le_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="debtrepayment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="debts_repayment_amount_positive",
            ),
        ),
    ]
