# Generated by Django 5.2.15 on 2026-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "telegram_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(blank=True, default="", max_length=64)),
                ("username", models.CharField(blank=True, default="", max_length=32)),
                ("language_code", models.CharField(default="uz", max_length=8)),
                (
                    "default_currency",
                    models.CharField(
                        choices=[("UZS", "so'm"), ("RUB", "rubl"), ("USD", "dollar")],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                ("onboarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_user",
            },
        ),
    ]
