# Generated by Django 5.2.15 on 2026-06-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "UZS"), ("RUB", "RUB"), ("USD", "USD")],
                        max_length=3,
                    ),
                ),
                ("rate_to_uzs", models.DecimalField(decimal_places=6, max_digits=15)),
                ("date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("cbu.uz", "CBU.uz")], default="cbu.uz", max_length=16
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "currencies_exchangerate",
                "ordering": ["-date", "currency"],
                "indexes": [
                    models.Index(
                        fields=["currency", "-date"],
                        name="currencies__currenc_4ef5e0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency", "date"),
                        name="currencies_rate_unique_currency_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate_to_uzs__gt", 0)),
                        name="currencies_rate_positive",
                    ),
                ],
            },
        ),
    ]
