# Generated by Django 5.2.15 on 2026-06-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Kirim"),
                            ("expense", "Chiqim"),
                            ("debt_lent", "Qarz berdim"),
                            ("debt_borrowed", "Qarz oldim"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "so'm"), ("RUB", "rubl"), ("USD", "dollar")],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                ("category_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "counterparty",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("date", models.DateField()),
                ("note", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "transactions_transaction",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="transaction_user_id_8af7f1_idx"),
                    models.Index(
                        fields=["user", "type", "date"],
                        name="transaction_user_id_feac84_idx",
                    ),
                    models.Index(
                        fields=["user", "is_deleted"],
                        name="transaction_user_id_57ca2a_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="transactions_amount_positive",
                    )
                ],
            },
        ),
    ]
