# Generated by Django 5.2.15 on 2026-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_remove_transaction_category_id_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
