# Generated by Django 5.2.15 on 2026-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_transaction_settled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="debt_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
