# Generated by Django 5.2.15 on 2026-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_transaction_debt_reminder_sent_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("income", "Kirim"),
                    ("expense", "Chiqim"),
                    ("debt_lent", "Qarz berdim"),
                    ("debt_borrowed", "Qarz oldim"),
                    ("debt_repaid_by_me", "Qarz qaytardim"),
                    ("debt_repaid_to_me", "Qarz qaytarib olindi"),
                ],
                max_length=24,
            ),
        ),
    ]
