# Generated by Django 5.2.15 on 2026-06-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Kirim"), ("expense", "Chiqim")],
                        max_length=8,
                    ),
                ),
                ("slug", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=64)),
                ("emoji", models.CharField(default="📁", max_length=8)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL identifies a preset visible to every user.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "categories_category",
                "ordering": ["type", "name"],
                "indexes": [
                    models.Index(fields=["user", "type"], name="categories__user_id_135dec_idx"),
                    models.Index(fields=["type", "slug"], name="categories__type_87432f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type", "slug"),
                        name="categories_unique_slug_per_user_type",
                    )
                ],
            },
        ),
    ]
