# Generated by Django 5.2.15 on 2026-06-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("categories", "0002_seed_presets"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryHide",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_for",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_categories",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "categories_categoryhide",
                "indexes": [models.Index(fields=["user"], name="categories__user_id_6d2392_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"),
                        name="categories_unique_hide_per_user",
                    )
                ],
            },
        ),
    ]
