# Generated by Django 5.2.15 on 2026-06-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_show_converted"),
        ("categories", "0003_categoryhide"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Kirim"),
                            ("expense", "Chiqim"),
                            ("debt_lent", "Qarz berdim"),
                            ("debt_borrowed", "Qarz oldim"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[("UZS", "so'm"), ("RUB", "rubl"), ("USD", "dollar")],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                (
                    "schedule_kind",
                    models.CharField(
                        choices=[("monthly", "Oylik"), ("weekly", "Haftalik")],
                        max_length=8,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_dispatch_at", models.DateField()),
                (
                    "last_dispatched_on",
                    models.DateField(
                        blank=True,
                        help_text="Date the last Transaction was materialized (idempotency key).",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurring_schedules",
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_schedules",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_schedule",
                "ordering": ["-is_active", "next_dispatch_at", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="recurring_s_user_id_69f597_idx",
                    ),
                    models.Index(
                        fields=["is_active", "next_dispatch_at"],
                        name="recurring_s_is_acti_c46552_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="recurring_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("day_of_month__gte", 1),
                                ("day_of_month__lte", 31),
                                ("schedule_kind", "monthly"),
                            ),
                            models.Q(
                                ("day_of_week__gte", 0),
                                ("day_of_week__lte", 6),
                                ("schedule_kind", "weekly"),
                            ),
                            _connector="OR",
                        ),
                        name="recurring_schedule_cadence_valid",
                    ),
                ],
            },
        ),
    ]
