# Generated by Django 5.2.15 on 2026-06-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_show_converted"),
        ("categories", "0003_categoryhide"),
        ("recurring", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recurringschedule",
            name="recurring_schedule_cadence_valid",
        ),
        migrations.AddField(
            model_name="recurringschedule",
            name="defer_until",
            field=models.DateField(
                blank=True,
                help_text="If set, the prompt is hidden from the home page until this date.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="schedule_kind",
            field=models.CharField(
                choices=[
                    ("daily", "Har kuni"),
                    ("weekly", "Haftalik"),
                    ("monthly", "Oylik"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("day_of_month__gte", 1),
                        ("day_of_month__lte", 31),
                        ("schedule_kind", "monthly"),
                    ),
                    models.Q(
                        ("day_of_week__gte", 0),
                        ("day_of_week__lte", 6),
                        ("schedule_kind", "weekly"),
                    ),
                    ("schedule_kind", "daily"),
                    _connector="OR",
                ),
                name="recurring_schedule_cadence_valid",
            ),
        ),
    ]
