# Generated by Django 5.2.15 on 2026-06-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_user_show_converted"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushQueueItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recurring_fired", "Takrorlanuvchi yozildi"),
                            ("debt_due", "Qarz muddati keldi"),
                            ("daily_digest", "Kunlik xulosa"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_queue_items",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_push_queue",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "kind"], name="notificatio_user_id_913f4a_idx"),
                    models.Index(fields=["sent_at"], name="notificatio_sent_at_ca6770_idx"),
                ],
            },
        ),
    ]
