# Generated by Django 5.2.15 on 2026-07-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushqueueitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("recurring_fired", "Takrorlanuvchi yozildi"),
                    ("debt_due", "Qarz muddati keldi"),
                    ("daily_digest", "Kunlik xulosa"),
                    ("debt_reminder", "Qarz eslatmasi"),
                ],
                max_length=32,
            ),
        ),
    ]
