# Generated by Django 5.2.15 on 2026-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_pushqueueitem_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminMessageLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_chat_id", models.BigIntegerField()),
                ("admin_message_id", models.BigIntegerField()),
                ("user_telegram_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["admin_chat_id", "admin_message_id"],
                        name="notificatio_admin_c_87df3e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admin_chat_id", "admin_message_id"),
                        name="notifications_admin_message_link_unique",
                    )
                ],
            },
        ),
    ]
